### ISSUE TITLE
không bắt được request

### ISSUE THREAD

**Issue by phapntm** [thedemons/FiddlerMomoPlugin#1]
đã cài cer fiddler vào android rồi nhưng vẫn không bắt được request từ momo. 
dòng của nó bị mờ đi

**Comment by thedemons** [comment]
Hi @phapntm

Mình xin phép đóng issue này với lý do như sau:
1. Bạn không cung cấp đủ thông tin nên mình không thể biết được bạn đang gặp lỗi gì.
2. Đây không phải là vấn đề của plugin, mà là do cách setup của bạn.

**Comment by phapntm** [comment]
Lỗi này không bắt được request, nó mờ đi. Bạn cần thông tin gì thì hỏi để mình cung cấp chứ.
Cái này nó liên quan tới plugin mà. Phải thực hiện được bước này thì mới xài plugin của bạn được. 
Nếu bạn k giúp thì để ai đó biết trả lời giúp mình cũng được chứ sao lại close as completed??? Đã complete đâu

**Comment by thedemons** [comment]
@phapntm 

## Issue này không phải là vấn đề của plugin

Vấn đề của plugin ví dụ như những trường hợp sau đây:
- Đã cài đặt thành công nhưng plugin không giải mã.
- Plugin crash trong trường hợp x.
- Fiddler không nhận dạng và load được plugin.
- ...


## Bạn đưa ra quá ít thông tin để người khác có thể trả lời
1. Câu hỏi của bạn không có đầu đuôi, sai chính tả.
2. Câu `dòng của nó bị mờ đi` quá thiếu thông tin để biết `dòng` ở đây là chỉ cái gì và `mờ` có nghĩa là gì.
3. Nếu muốn được người khác giúp đỡ, hãy đặt một issue với các thông tin đầy đủ sau đây:
    - Mô tả chi tiết lỗi bạn đang gặp phải.
    - Các bước chính xác để có thể tái tạo lại lỗi.
    - Bạn đang dùng Fiddler phiên bản nào, và dùng trên giả lập/thiết bị gì.
    - Các giải pháp bạn đã thử, và kết quả của nó.
    - Kèm hình ảnh mô tả lỗi và các thông tin khác nếu cần thiết.
4. Bạn có thể tham khảo [How to Ask](https://stackoverflow.com/help/how-to-ask) trên stackoverflow để biết thêm.

## Người khác không có nghĩa vụ giải quyết vấn đề của bạn
Đây có lẽ là điều dĩ nhiên nhưng hình như bạn đang không biết điều này, đây là plugin phi lợi nhuận nên cả tác giả và cộng đồng đều không có nghĩa vụ phải giải quyết vấn đề cá nhân của bạn.

## Kết luận
Hãy tạo một issue mới với đầy đủ thông tin nêu trên, người khác sẽ có thể biết bạn đang gặp lỗi gì và hỗ trợ bạn.
